apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-cluster
spec:
  destination:
    namespace: 'openshift-gitops'
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/gitlab-runner-operator
    repoURL: https://github.com/ajaykanse/control-plane
    directory:
      recurse: true
  syncPolicy:
    automated: {}
