apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: openshift-cert-manager-operator
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
      configMapRef: acm-placement
      labelSelector:
        matchLabels:
          cluster.open-cluster-management.io/placement: ocp-cert-manager-placement
      requeueAfterSeconds: 180
  template:
    metadata:
      annotations:
        app.kubernetes.io/instance: '{{name}}'
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      labels:
        velero.io/exclude-from-backup: "true"
      name: '{{name}}-ocp-cert-manager'
    spec:
      destination:
        namespace: openshift-gitops
        server: '{{server}}'
      project: default
    # in ocp 4.14 multiple sources can be added ( see gitlab operator appset)
    # Due to this u cant see app details link in ACM UI
      source:
        helm:
          releaseName: ocp-cert-manager-operator
          valueFiles:
          - values.yaml
          parameters:
          - name: version
            value: "v1.12.1"
          - name: approval
            value: "Automatic"
        path: components/ocp-cert-manager-operator/ocp-cert-manager
        repoURL: https://github.com/ajaykanse/gitops-standard-repo-template.git
        targetRevision: acm
      # - helm:
      #     releaseName: david-test
      #     valueFiles:
      #     - values.yaml
      #   path: charts/david-test2
      #   repoURL: git@gitlab.com:ddreggors-openshift/ocp-post-install-charts.git
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: ocp-cert-manager-placement
  namespace: openshift-gitops
spec:
  clusterSets:
  - production


