default:
  app:
    enabled: true
    enableAutoSync: true
    autoSyncPrune: false
    project: cluster-config
    labels:
      app-source: cluster-prod
      repo: cluster-config
    destination:
      namespace: openshift-gitops
      server: https://api.cluster1.sandbox2894.opentlc.com:6443
    source:
      repoURL: https://github.com/ajaykanse/gitops-standard-repo-template.git
      targetRevision: acm-test
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true  
    - FailOnSharedResource=true
    - RespectIgnoreDifferences=true
    - CreateNamespace=false      