apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../components/gitlab-runner-operator/

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: stable
    target:
      kind: Subscription
  - patch: |-
      - op: replace
        path: /spec/startingCSV
        value: gitlab-runner-operator.v1.20.0
    target:
      kind: Subscription 